name: relo
description: "Mạng xã hội Relo"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  http: ^1.5.0
  fluttertoast: ^9.0.0
  firebase_core: ^3.3.0
  firebase_messaging: ^15.0.0
  convex_bottom_bar: ^3.2.0
  font_awesome_flutter: ^10.7.0
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.0.0
  dio: ^5.4.1
  sqflite: ^2.0.0+4
  path: ^1.8.3
  connectivity_plus: ^4.0.1
  web_socket_channel: ^2.4.0
  uuid: ^4.4.0
  intl: ^0.19.0
  flutter_sound: ^9.2.13
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  audioplayers: ^6.0.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  video_player: ^2.9.0
  chewie: ^1.7.1
  cached_network_image: ^3.4.0
  photo_view: ^0.15.0
  photo_manager: ^3.7.1
  photo_manager_image_provider: ^2.2.0
  lucide_icons: ^0.257.0
  shimmer: ^3.0.0
  extended_image: ^8.2.1
  camera: ^0.10.6
  video_thumbnail: ^0.5.0
  visibility_detector: ^0.4.0+2
  flutter_local_notifications: ^17.2.3
  flutter_animate: ^4.5.0
  pull_to_refresh: ^2.0.0
  timeago: ^3.7.0
  filesize: ^2.0.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.1
  build_runner: ^2.4.6
  json_serializable: ^6.7.0
  
flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/none_images/

#Cấu hình Icon
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_logo.png"
  adaptive_icon_foreground: "assets/icons/app_logo.png"

#Cấu hình splash
flutter_native_splash:
  color: "#7A2FC0"
  image: assets/icons/icon.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
  android_12:
    color: "#7A2FC0"
    image: assets/icons/icon.png
